[package]
name = "fluxstream"
version = "0.1.0"
authors = ["Sridhar Ananthakrishnan <itsmycodehub@gmail.com>"]
edition = "2021"

[dependencies]
hyper = "0.14.18"
tokio = { version = "1.14.0", features = ["full"] }
futures = "0.3.17"